markdown: kramdown
highlighter: rouge
permalink: /blog/:categories/:year-:month-:day/:title.html
excerpt_separator: "<!-- more -->"

github: walkerljl
author: "walkerljl"
email: xingxun#walkerljl.com
name: "文档库"
url: http://walkerljl.org
domain: www.walkerljl.org
all_categories: [
["programlanguage", "编程语言","/blog/programlanguage.html"],
["designpattern", "设计模式","/blog/designpattern.html"],
["database", "数据库","/blog/database.html"],
["security", "安全","/blog/security.html"],
["frontend", "前端","/blog/frontend.html"],
["test", "测试","/blog/test.html"],
["component", "组件","/blog/component.html"],
["tool", "工具","/blog/tool.html"],
["site", "建站","/blog/site.html"],
["other", "其它","/blog/other.html"],
["about", "关于","/about.html"]
]

paginate: 8
paginate_path: "posts/page:num"
timezone: America/Los_Angeles

collections:
  docs:
    output: true

gems:
 - jekyll-paginate
