markdown: kramdown
highlighter: pygments
permalink: /posts/:title.html
excerpt_separator: "<!-- more -->"

github: walkerljl
author: "walkerljl"
email: xingxun#walkerljl.com
name: "walkerljl个人博客"
url: http://walkerljl.org
domain: www.walkerljl.org
all_categories: [
["programlanguage", "编程语言","/posts/programlanguage.html"],
["tool", "工具","/posts/tool.html"],
["other", "其它","/posts/other.html"],
["about", "关于","/about.html"]
]

paginate: 8
paginate_path: "posts/page:num"
timezone: America/Los_Angeles

collections:
  docs:
    output: true

gems:
 - jekyll-paginate
